
version: '3.1'

services:
    redis:
        restart: always
        image: redis:6.2.4-alpine
        volumes:
            - "./deploy/redis:/data"

    webserver:
        depends_on: 
            - db
            - redis
        image: daniellandau1998/node-server
        command: node webserver.js
        container_name: nodejs
        restart: always
        volumes:
            - ".././server:/var/project/src"
        ports:
            - "443:443"
            - "80:80"
        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
            SQL_HOST: db
            SQL_PORT: 3306
            SQL_USER: node-webserver
            SQL_DATABASE: node_db
            SQL_TABLE_NAME: dev5
            HTTPS_ENABLE: 'true'
            JWT_ENCRYPTION_ENABLE: 'false'
        env_file:
            - sql-config.env
            - jwt-config.env
            - https-config.env

    db:
        image: mysql:5.7
        container_name: database
        restart: always
        volumes:
            - "./deploy/mysql_data:/var/lib/mysql"
        ports:
            - "3001:3306"
        environment:
           MYSQL_USER: node-webserver
           MYSQL_DATABASE: node_db
        env_file:
            - sql-config.env
volumes:
    cache:
    src_data:
    db_data: