
version: '3.1'

services:
    redis:
        restart: always
        image: redis:6.2.4-alpine
        volumes:
            - ./deploy/redis:/data

    webserver:
        depends_on: 
            - db
            - redis
        image: daniellandau1998/node-server
        command: node webserver.js
        container_name: nodejs
        restart: always
        volumes:
            - ../server:/var/project/src
            - ./deploy/env/certs:/var/project/src/certs
        ports:
            - 443:443
            - 80:80

        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
            SQL_HOST: db
            SQL_PORT: 3306
            SQL_USER: nodeServer
            SQL_DATABASE: node_db
            SQL_TABLE_NAME: deploy3

            HTTPS_ENABLE: 'false'
            SSL_KEY:  ./certs/ssl.key
            SSL_CERT: ./certs/ssl.crt

            JWT_ENCRYPTION_ENABLE: 'false'
            JWT_SIGNING_KEY: ./certs/jwt.private.key
            JWT_VERIFY_KEY: ./certs/jwt.public.key
        env_file:
            - ./deploy/env/sql-config.env
            - ./deploy/env/jwt-config.env

    db:
        image: mysql:5.7
        container_name: database
        restart: always
        volumes:
            - ./deploy/mysql:/var/lib/mysql
        ports:
            - 3001:3306

        environment:
           MYSQL_USER: nodeServer
           MYSQL_DATABASE: node_db
        env_file:
            - ./deploy/env/sql-config.env

volumes:
    cache:
    certs:
    src_data:
    db_data: