
version: '3.1'

services:
    redis:
      restart: always
      image: redis:6.2.4-alpine
      volumes:
        - "./deploy/redis:/data"
    webserver:
        depends_on: 
            - db
        image: daniellandau1998/node-server
        command: node webserver.js
        container_name: nodejs
        restart: always
        volumes:
            - "./doodles:/var/project/src/public/doodles"
            - "./cache:/var/project/src/cache"
        ports:
            - "443:443"
            - "80:80"
        environment: 
            REDIS_HOST: redis
            SQL_HOST: db
            SQL_PORT: 3306
            SQL_USER: nodeServer
            SQL_DATABASE: node_db
            SQL_TABLE_NAME: deploy2
            HTTPS_ENABLE: 'true'
            JWT_ENCRYPTION_ENABLE: 'true'
        env_file:
            - ./env/sql-config.env
            - ./env/jwt-config.env
            - ./env/https-config.env

    db:
        image: mysql:5.7
        container_name: database
        restart: always
        volumes:
                - "./mysql_data:/var/lib/mysql"
        ports:
            - "3001:3306"
        environment:
           MYSQL_USER: nodeServer
           MYSQL_DATABASE: node_db
        env_file:
            - ./env/sql-config.env
volumes:
    src_data:
    db_data:
