
version: '3.1'

services:
    webserver:
        depends_on: 
            - db
        image: daniellandau1998/node-server
        command: node webserver.js
        container_name: nodejs
        restart: always
        volumes:
            - "./doodles:/var/project/src/public/doodles"
            - "./cache:/var/project/src/cache"
        ports:
            - "443:443"
            - "80:80"
        environment: 
            AUTH2_USER: 'd.landau,admin'
            SQL_HOST: db
            SQL_PORT: 3306
            SQL_DATABASE: node_db
            SQL_TABLE_NAME: deploy_1
            SQL_USER: node-webserver
            SQL_PASSWORD: WPi8tQ(_rWOI{BKqI<wsRDSLxtmiqeVMn7L[{S9juWkE}6wt
            HTTPS_ENABLE: 'true'
            JWT_ENCRYPTION_ENABLE: 'true'
        env_file:
            - ./env/jwt-config.env
            - ./env/https-config.env

    db:
        image: mysql:5.7
        container_name: database
        restart: always
        volumes:
                - "./mysql_data:/var/lib/mysql"
        ports:
            - "3001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: M_MWeaX(3hPcDhU8Feg]hVS6NIiuKvwr66(]6b9eYRGkHZvb
            MYSQL_PASSWORD: WPi8tQ(_rWOI{BKqI<wsRDSLxtmiqeVMn7L[{S9juWkE}6wt
            MYSQL_USER: node-webserver
            MYSQL_DATABASE: node_db
volumes:
    src_data:
    db_data:
