
version: '3.1'

services:
    certbot:
      restart: always
      image: daniellandau1998/nginx-server:certbot
      command: sh /etc/nginx/start.sh
      ports:
        - 80:80
      volumes:
        - ./nginx:/etc/nginx/
        - ./certs/certbot:/etc/letsencrypt/

    redis:
      restart: always
      image: redis:6.2.4-alpine
      volumes:
        - ./redis:/data
        
    webserver:
        depends_on: 
            - db
            - certbot
        image: daniellandau1998/node-server
        command: node webserver.js
        container_name: nodejs
        restart: always
        volumes:
            - ./doodles:/var/project/src/public/doodles
            - ./certs:/var/project/src/certs
        ports:
            - 443:443

        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
            SQL_HOST: db
            SQL_PORT: 3306
            SQL_USER: nodeServer
            SQL_DATABASE: node_db
            SQL_TABLE_NAME: deploy2

            HTTPS_ENABLE: 'true'
            SSL_KEY:  /certs/certbot/live/www.daniel-testing.cloud/cert.pem
            SSL_CERT: /certs/certbot/live/www.daniel-testing.cloud/privkey.pem

            JWT_ENCRYPTION_ENABLE: 'true'
            JWT_SIGNING_KEY: /certs/jwt.private.key
            JWT_VERIFY_KEY: /certs/jwt.public.key

        env_file:
            - ./env/sql-config.env
            - ./env/jwt-config.env

    db:
        image: mysql:5.7
        container_name: database
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3001:3306

        environment:
           MYSQL_USER: nodeServer
           MYSQL_DATABASE: node_db
        env_file:
            - ./env/sql-config.env
volumes:
    nginx:
    letsencrypt:
    cache:
    doodles:
    certs:
    db_data:
