name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  HOST: daniel-testing.cloud:2376
  USERNAME: daniellandau1998
  IMAGE_NAME: node-server
  IMAGE_TAG: latest
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo CA_FILE > ./ca.pem
        env:
         CA_FILE : ${{secrets.CA}}
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker version
      - run: env
      - run: echo CA_FILE > ./ca.pem
        env:
         CA_FILE : ${{secrets.CA}}
      - run: cat ./ca.pem
      - run: docker --tlsverify -H ${{ env.HOST }} --tlscacert=${{ secrets.CA }} --tlscert=${{ secrets.CLIENT_CERT }} --tlskey=${{ secrets.CLIENT_KEY }} ps
      - run: docker-compose --tlsverify -H ${{ env.HOST }} --tlscacert=${{ secrets.CA }} --tlscert=${{ secrets.CLIENT_CERT }} --tlskey=${{ secrets.CLIENT_KEY }} -f /root/PROJECT__React-app-1/docker/dc-web-db.yaml pull 
      - run: dockerx
      
      - name: Login Docker Account
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - run: npm install
      - run: npm run build --if-present
      
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
         context: .
         file: ./docker/df-webserver     # Path to the Dockerfile
         push: ${{ github.event_name != 'pull_request' }}
         tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
         
          
    
