name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  HOST: daniel-testing.cloud
  USERNAME: daniellandau1998
  IMAGE_NAME: node-server
  IMAGE_TAG: latest
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Login Docker Account
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - run: npm install
      - run: npm run build --if-present
         
          
    
